# Generated by Django 4.2.7 on 2025-09-01 23:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agritrust_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produce',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='produce',
            unique_together={('farmer', 'name', 'harvest_date')},
        ),
    ]
